### ISSUE TITLE
`intros` non-predicate patterns

### ISSUE THREAD

**Issue by h0nzZik** [kframework/matching-logic-prover#42]
Currently, `intros H` check whether the LHS is a predicate pattern. I believe there is no need for it - the deduction theorem works even for non-predicate patterns. Therefore I would like to relax that restriction.

**Comment by xc93** [comment]
This is the deduction theorem:
Gamma U {psi} |- phi   iff   Gamma |- \floor{psi} -> phi
where psi has no free variables. 
If psi is a predicate pattern then \floor{psi} = psi, so we have
Gamma U {psi} |- phi   iff   Gamma |- psi -> phi
which is the most common form we use in practice (from right to left).

**Comment by h0nzZik** [comment]
Oh, I see, I didn't notice the \floor. Thanks.
